### ISSUE TITLE
 Swift Error After Updating React Native 0.73.6

### ISSUE THREAD

**Issue by redbluenat** [refiner-io/mobile-sdk-react-native#22]
Hi everyone,

I recently updated my React Native project to use the following versions:

```
"react-native": "0.73.6",
"expo": "50",
"react": "18.2.0",
```

After updating, I started encountering a Swift error when using the latest version of Refiner:

`"refiner-react-native": "1.3.10",`

<img width="428" alt="Screenshot 2024-07-08 at 4 42 11 pm" src="https://github.com/refiner-io/mobile-sdk-react-native/assets/15861135/7f0df728-73e1-4072-a684-5e27d3509b7c">

Undefined symbol: __swift_FORCE_LOAD_$_swiftXPC

Has anyone else experienced this issue or have any recommendations on how to resolve it?

Thank you in advance for your help!

**Comment by tekinalper** [comment]
Hi, can you try the new version 1.3.12 and let me know if the issue is resolved?

**Comment by redbluenat** [comment]
@tekinalper Unfortunately, it is still happening. My project builds without any issues until I add this library.

**Comment by tekinalper** [comment]
@redbluenat what is your xcode version?

**Comment by redbluenat** [comment]
@tekinalper Xcode - Version 15.0.1

**Comment by tekinalper** [comment]
@redbluenat Do you have a chance to upgrade and try with 15.4?

**Comment by redbluenat** [comment]
@tekinalper  I can update to a maximum of version 15.2 because that is what App Center supports currently. Do you think this version will be sufficient?

**Comment by tekinalper** [comment]
@redbluenat I see. Most probably not :/ https://forums.developer.apple.com/forums/thread/749915 
Looks like at least version 15.3 and later.

**Comment by redbluenat** [comment]
@tekinalper xcode update fixed the issue! Thank you for your support :)

**Comment by tekinalper** [comment]
I'm happy to hear that :)
