### ISSUE TITLE
Linking issue just after integrating npm and pod install

### ISSUE THREAD

**Issue by MichaelRay23** [refiner-io/mobile-sdk-react-native#3]
<img width="829" alt="Screenshot 2022-08-23 at 10 24 45 AM" src="https://user-images.githubusercontent.com/109672307/186073003-7de49dff-502a-47ec-ba98-184ccb0d248a.png">

**Comment by chezmo** [comment]
Thanks a lot for reporting this @MichaelRay23. We've just released a new major version which I hope fixes this issue. Could you please give it another try?

**Comment by MichaelRay23** [comment]
No,  we have different issue now after updating to new version

<img width="1141" alt="Screenshot 2022-09-14 at 11 02 54 AM" src="https://user-images.githubusercontent.com/109672307/190079502-85f840e8-136c-402c-a286-4073276bcbbb.png">

**Comment by chezmo** [comment]
Just a guess for now: The "identifyUser" method changed in the new version and you need to provide an additional `signagure`parameter. The parameter can be null.
https://github.com/refiner-io/mobile-sdk-react-native#identify-user

**Comment by MichaelRay23** [comment]
But I haven't used still any code of refiner like identify or initialise ,just install npm and run the project then also this error occurred.

**Comment by chezmo** [comment]
ok! Thanks for the update and your patience. We'll look into this right away.

**Comment by chezmo** [comment]
Unfortunately we are not able to reproduce this issue at the moment. Are you able to build an run our [sample project](https://github.com/refiner-io/mobile-sdk-react-native/tree/main/example)?

**Comment by MichaelRay23** [comment]
yes , but from you sample code example, I was not able to see your sample survey but I have added signature and now I can see.

**Comment by chezmo** [comment]
Thank you for your patience Michael! Happy to hear that the issue is now resolved.

**Comment by MichaelRay23** [comment]
Hello @chezmo , again issue is coming , this is same as arc semantic issue.
I have tried all possible solutions but not getting success.

**Comment by SwapnilRathore** [comment]
I am having the same issue after installation

**Comment by tekinalper** [comment]
Closing the issue due to inactivity. Please try latest version published.
