### ISSUE TITLE
Missing Changelog, Release Notes, Git Tags

### ISSUE THREAD

**Issue by gupta-ji6** [refiner-io/mobile-sdk-react-native#7]
## Issue Description

Hi, we use Refiner RN SDK in our app and recently did an exercise to update all dependencies in the app.

While trying to upgrade `refiner-react-native`, we couldn't find any `CHANGELOG.md` file, GitHub Releases/Tags which could help us with upgrading the SDK from `0.0.8` to the latest.

I would highly recommend you folks prioritize adding changelogs in the SDK, or else it gonna get messier day by day to upgrade.

**Comment by tekinalper** [comment]
Hi, thanks for the feedback. We'll consider it from now on for further versions. Apologies for the lack of detailed instructions for the upgrade.
