### ISSUE TITLE
Can't compile the android app 

### ISSUE THREAD

**Issue by redbluenat** [refiner-io/mobile-sdk-react-native#9]
Since yesterday evening, I haven't been able to compile the app. I was using version 1.2.0, and even after updating to 1.2.2 today, it still doesn't work.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':refiner-react-native:compileDebugJavaWithJavac'.
> javax/xml/bind/JAXBException

/.gradle/caches/transforms-3/56379bbc02a6bfdf4cabae7a53428317/transformed/jetified-refiner-1.3.0-rc1.aar (No such file or directory)

**Comment by redbluenat** [comment]
This is a fix:

https://github.com/refiner-io/mobile-sdk-react-native/pull/8

@tekinalper @chezmo @aniltaskiran, any chance to merge it soon, or do I need to fork your repo?

**Comment by tekinalper** [comment]
> This is a fix:
> 
> https://github.com/refiner-io/mobile-sdk-react-native/pull/8
> 
> @tekinalper @chezmo @aniltaskiran, any chance to merge it soon, or do I need to fork your repo? 
> 
> 
> 

@redbluenat  we're working on a new version (in develop branch) and will be released soon. The fix has already been done for the new version.

**Comment by mohit23x** [comment]
@tekinalper any ETA when will the fix will be released?

**Comment by tekinalper** [comment]
v1.3.1 released
